python3 train.py \
    --epochs 30 --batch-size 512 --seed 42 \
    --model_type fc_conv --dataset_type fmnist --latent_space_size 10 \
    --do_augs False \
    --lr 1e-3 --m1 40 --m2 50 \
    --optimizer adam \
    --do_running_mean False --img_loss_weight 1.0 --kl_loss_weight 1.0 \
    --image_loss_type bce --ssim_window_size 5 \
    --print-freq 10 \
    --lognumber fmnist_fc_conv_l10_rebalance_no_norm \
    --tensorboard True --tensorboard_images True \
